sudo: required
dist: trusty

# language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - dev

services:
  - mysql 
  - xvfb

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - PATH="$TRAVIS_BUILD_DIR/vendor/bin:$PATH"
    - WP_CLI_BIN_DIR="$TRAVIS_BUILD_DIR/vendor/bin"
    - WP_VERSION=latest WP_MULTISITE=0
    - NODE_VERSION="12.0"
    
matrix:
  include:
    - language: php
      php: 7.2
      env: WP_VERSION=latest
      before_script:
        # - sudo apt-get update
        # - sudo apt-get install apache2 libapache2-mod-fastcgi
        # # enable php-fpm
        # - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
        # - sudo a2enmod rewrite actions fastcgi alias
        # - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        # - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
        # - sudo chown -R travis:travis /var/lib/apache2/fastcgi
        # - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
        # # configure apache virtual hosts
        # - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
        # - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
        # - sudo service apache2 restart

        - export PATH="$HOME/.composer/vendor/bin:$PATH"
        - |
          if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
            echo "TRAVIS_BUILD_DIR... $TRAVIS_BUILD_DIR"
            phpenv config-rm xdebug.ini
          else
            echo "TRAVIS_BUILD_DIR... $TRAVIS_BUILD_DIR"
            echo "xdebug.ini does not exist"
          fi
        # - |
        #   if [[ ! -z "$WP_VERSION" ]] ; then
        #     bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
        #     composer global require "phpunit/phpunit=5.*"
        #   fi
        - |
          if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
            composer global require wp-coding-standards/wpcs
            phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
          fi

        # Define vars.
        - export WP_VERSION=master
        - export WP_DEVELOP_DIR=/tmp/wordpress
        - export WP_CORE_DIR=/tmp/wordpress/src
        - export WP_CEPT_SERVER='127.0.0.1:8888'
        # Install WordPress
        - source travis.sh
        - install-wordpress
        - install_test_suite
        - move_things
        
        # Start up a web server.
        - php -S "$WP_CEPT_SERVER" -t "$WP_CORE_DIR" >/dev/null 2>&1 &
        # Start up the webdriver.
        #- phantomjs --webdriver=4444 >/dev/null 2>&1 &
        # - phantomjs --webdriver=4444 >/dev/null 2>&1 &

        #selenium
        - git clone https://github.com/srimaln91/selenium-installer.git
        - cd selenium-installer
        - sudo bash selenium_install.sh
        - selenium start &
        - cd ..
        
        # Install Codeception and WP Browser.
        # Doing this last gives the webdriver and server time to start up.
        - composer_and_wp_plugins_install_update

      script:
        - |
          if [[ ! -z "$WP_VERSION" ]] ; then
            phpunit
            WP_MULTISITE=1 phpunit
          fi
        - |
          if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
            phpcs
          fi

        - php vendor/bin/codecept build
        - php vendor/bin/codecept run --steps --debug
        # - vendor/bin/wpcept run

    # - language: node_js
    #   node_js:
    #     - "10.21.0"
    #   script: npm test #node_modules/karma/bin/karma start karma.conf.js --single-run
    #   before_install:
    #     - export DISPLAY=:99.0
    #     - sh -e /etc/init.d/xvfb start
    #   before_script:
    #     - npm install

    #- php: 7.1
    #  env: WP_VERSION=latest
    #- php: 7.0
    #  env: WP_VERSION=latest
    #- php: 5.6
    #  env: WP_VERSION=latest
    #- php: 5.6
    #  env: WP_VERSION=trunk
    #- php: 5.6
    #  env: WP_TRAVISCI=phpcs
    #- php: 5.3
    #  env: WP_VERSION=latest
    #  dist: precise


